### PR TITLE
7903771: Feature Tests - Adding five JavaTest GUI legacy automated test scripts

### PR DESCRIPTION
**Pull request by gollayadav**
Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macos.

1. CustomReport9.java
2. MenuItems01.java
3. MenuItems02.java
4. Config_Load6_1.java
5. Config_Load8.java

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [CODETOOLS-7903771](https://bugs.openjdk.org/browse/CODETOOLS-7903771): Feature Tests - Adding five JavaTest GUI legacy automated test scripts (**Sub-task** - P3)

### Reviewers
 * [Dmitry Bessonov](https://openjdk.org/census#dbessono) (@dbessono - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtharness.git pull/79/head:pull/79` \
`$ git checkout pull/79`

Update a local copy of the PR: \
`$ git checkout pull/79` \
`$ git pull https://git.openjdk.org/jtharness.git pull/79/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 79`

View PR using the GUI difftool: \
`$ git pr show -t 79`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtharness/pull/79.diff">https://git.openjdk.org/jtharness/pull/79.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtharness/pull/79#issuecomment-2214069544)

### CODE REVIEW

**Review by dbessono — APPROVED** [review]

**Comment by gollayadav** [comment]
> @gollayadav This pull request is now open

@dbessono Thank You for your time in reviewing the test scripts.

**Pull request closed without merging**
