### PR TITLE
7903688: Feature Tests - Adding five JavaTest GUI legacy automated test scripts

### PR DESCRIPTION
**Pull request by gollayadav**
Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macos.

1. Markers13.java
2. Markers21.java
3. ReportCreate11.java
4. ReportCreate13.java
5. ReportCreate14.java

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [CODETOOLS-7903688](https://bugs.openjdk.org/browse/CODETOOLS-7903688): Feature Tests - Adding five JavaTest GUI legacy automated test scripts (**Sub-task** - P3)

### Reviewers
 * [Dmitry Bessonov](https://openjdk.org/census#dbessono) (@dbessono - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtharness.git pull/61/head:pull/61` \
`$ git checkout pull/61`

Update a local copy of the PR: \
`$ git checkout pull/61` \
`$ git pull https://git.openjdk.org/jtharness.git pull/61/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 61`

View PR using the GUI difftool: \
`$ git pr show -t 61`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtharness/pull/61.diff">https://git.openjdk.org/jtharness/pull/61.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtharness/pull/61#issuecomment-1994642698)

### CODE REVIEW

**Review by dbessono — APPROVED** [review]
Thank you for the tests, checked additionally - they pass for me on Linux.

**Comment by gollayadav** [comment]
> Thank you for the tests, checked additionally - they pass for me on Linux.

Thanks for your time in reviewing the test scripts.

**Pull request closed without merging**
