### PR TITLE
7903076: Feature Tests - Adding five JavaTest GUI legacy automated feature test scripts

### PR DESCRIPTION
**Pull request by gollayadav**
Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine.

1.Browse5.java
2.Browse8.java
3.Config_Edit3.java
4.Config_Edit4.java
5.Config_Edit5.java

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Issue
 * [CODETOOLS-7903076](https://bugs.openjdk.java.net/browse/CODETOOLS-7903076): Feature Tests - Adding five JavaTest GUI legacy automated feature test scripts

### Reviewers
 * [Dmitry Bessonov](https://openjdk.java.net/census#dbessono) (@dbessono - Committer)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.java.net/jtharness pull/21/head:pull/21` \
`$ git checkout pull/21`

Update a local copy of the PR: \
`$ git checkout pull/21` \
`$ git pull https://git.openjdk.java.net/jtharness pull/21/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 21`

View PR using the GUI difftool: \
`$ git pr show -t 21`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.java.net/jtharness/pull/21.diff">https://git.openjdk.java.net/jtharness/pull/21.diff</a>

</details>

### CODE REVIEW

**Comment by gollayadav** [comment]
I guess this PR is not required so closing this pull request.

**Review by dbessono — APPROVED** [review]

**Pull request closed without merging**
