### PR TITLE
Feature Tests - Adding five JavaTest GUI legacy automated test scripts

### PR DESCRIPTION
**Pull request by gollayadav**
Adding below automated legacy JavaTest GUI feature Test Scripts to the Jemmy regression suite and tested locally on three platforms(Linux, Windows, Mac OS) and working fine. Also verified with JDK8 on macos.

1.Markers1.java
1.Markers9.java
1.Markers10.java
1.Markers11.java
1.Markers12.java

---------
### Progress
- [x] Change must not contain extraneous whitespace

### Reviewers
 * [Dmitry Bessonov](https://openjdk.org/census#dbessono) (@dbessono - **Reviewer**)

### Reviewing
<details><summary>Using <code>git</code></summary>

Checkout this PR locally: \
`$ git fetch https://git.openjdk.org/jtharness.git pull/56/head:pull/56` \
`$ git checkout pull/56`

Update a local copy of the PR: \
`$ git checkout pull/56` \
`$ git pull https://git.openjdk.org/jtharness.git pull/56/head`

</details>
<details><summary>Using Skara CLI tools</summary>

Checkout this PR locally: \
`$ git pr checkout 56`

View PR using the GUI difftool: \
`$ git pr show -t 56`

</details>
<details><summary>Using diff file</summary>

Download this PR as a diff file: \
<a href="https://git.openjdk.org/jtharness/pull/56.diff">https://git.openjdk.org/jtharness/pull/56.diff</a>

</details>

### Webrev
[Link to Webrev Comment](https://git.openjdk.org/jtharness/pull/56#issuecomment-1843512731)

### CODE REVIEW

**Comment by gollayadav** [comment]
Could you please review this PR.

**Review by dbessono — APPROVED** [review]
Double checked - the tests pass for me.

**Comment by gollayadav** [comment]
Thanks for your time in reviewing the test scripts.

**Pull request closed without merging**
